FROM node:25.1-bookworm

ARG USER_NAME=node

RUN <<EOF
        apt-get update;
        apt-get install -y  \
        libpq-dev           \
        postgresql-client   \
        sudo                \
        git                 \
        vim                 \
        wget                \
        locales

        rm -rf /var/lib/apt/lists/*
        localedef -i pt_BR -c -f UTF-8 -A /usr/share/locale/locale.alias pt_BR.UTF-8

        usermod -aG sudo ${USER_NAME}
        usermod -s /bin/bash ${USER_NAME}
        echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
        echo 'parse_git_branch() { git rev-parse --is-inside-work-tree > /dev/null 2>&1 && echo "git:$(git symbolic-ref --short HEAD)" || exit 1; }' >> /home/${USER_NAME}/.bashrc;
        echo 'PS1=" \[\e[38;5;153m\]\u\[\e[m\] at \[\e[38;5;150m\]\h\[\e[m\] in \[\e[38;5;214m\]\w\[\e[m\] \033[0;91m\$(parse_git_branch)\[\e[m\]\n "' >> /home/${USER_NAME}/.bashrc;

        npm install -g @nestjs/cli
EOF

WORKDIR /app
USER node
SHELL ["/bin/bash", "-c"]

